/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class u640_CWrap */

#ifndef _Included_u640_CWrap
#define _Included_u640_CWrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     u640_CWrap
 * Method:    brodger
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_u640_CWrap_brodger
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
