/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class u640_CWrap */

#ifndef _Included_u640_CWrap
#define _Included_u640_CWrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     u640_CWrap
 * Method:    init
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_u640_CWrap_init
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     u640_CWrap
 * Method:    allocArray
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_u640_CWrap_allocArray
  (JNIEnv *, jobject, jlong);

/*
 * Class:     u640_CWrap
 * Method:    allocBuffer
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_u640_CWrap_allocBuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     u640_CWrap
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_u640_CWrap_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     u640_CWrap
 * Method:    brodger
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_u640_CWrap_brodger
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     u640_CWrap
 * Method:    process
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_u640_CWrap_process__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     u640_CWrap
 * Method:    process
 * Signature: (JLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_u640_CWrap_process__JLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
