/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __t508_u640_video_F642X264__
#define __t508_u640_video_F642X264__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jlong JNICALL Java_t508_u640_video_F642X264_init (JNIEnv *env, jobject, jint, jint, jfloat, jstring);
JNIEXPORT void JNICALL Java_t508_u640_video_F642X264_free (JNIEnv *env, jobject, jlong);
JNIEXPORT jint JNICALL Java_t508_u640_video_F642X264_write_1frame (JNIEnv *env, jobject, jlong, jbyteArray);
JNIEXPORT jint JNICALL Java_t508_u640_video_F642X264_close (JNIEnv *env, jobject, jlong);

#ifdef __cplusplus
}
#endif

#endif /* __t508_u640_video_F642X264__ */
